# Introduction to NumPy

NumPy, short for Numerical Python, stands as a robust and influential Python library dedicated to numerical computing. It holds a central role in scientific computing within the Python ecosystem, offering extensive support for handling large, multi-dimensional arrays and matrices. The library boasts an array of mathematical functions, adeptly designed to efficiently operate on these arrays. NumPy has established itself as a cornerstone in various fields, including data analysis, machine learning, image processing, and scientific {cite:p}`harris2020array,NumPyDocumentation`.
At its core, NumPy provides a versatile multidimensional array object, alongside several derived objects such as masked arrays and matrices. Along with this, it offers a vast array of routines specifically optimized for swift operations on arrays. These routines encompass a broad spectrum of functionalities, encompassing mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation, and much more. Overall, NumPy serves as an indispensable tool for a wide range of numerical computations and data manipulation tasks in Python.


## Installation:


NumPy is not a built-in library in Python, so you need to install it separately. You can use pip, the Python package manager, to install NumPy:

```
>>> pip install numpy
```

`````{admonition} Remark
:class: important
Google Colab (Colaboratory) is a cloud-based Jupyter notebook environment provided by Google, and it comes with a variety of popular data science libraries preinstalled, including NumPy, Pandas, Matplotlib, and more. 

`````

## Importing NumPy:
To use NumPy in your Python script or interactive session, you need to import it first:

In [1]:
import numpy as np

The common convention is to import NumPy as "np" for brevity.

## Creating NumPy Arrays:

NumPy's primary data structure is the ndarray (N-dimensional array). You can create a NumPy array using various methods, such as:


In [2]:
# From a list or tuple
arr1 = np.array([1, 2, 3, 4, 5])

# From nested lists
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Using built-in functions
zeros_arr = np.zeros((3, 4))    # 3x4 array of zeros
ones_arr = np.ones((2, 3))      # 2x3 array of ones
random_arr = np.random.rand(3, 3)  # 3x3 array of random values between 0 and 1

```{figure} Fig11.01.png
---
width: 500px
align: left
---
Visualizing np.array([1, 2, 3, 4, 5]).
```

## Basic Operations:

NumPy allows you to perform element-wise operations on arrays, making it convenient for mathematical computations:

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
result_add = a + b   # Output: [5 7 9]
print(result_add)

# Element-wise multiplication
result_mul = a * b   # Output: [4 10 18]
print(result_mul)

# Dot product (inner product)
dot_product = np.dot(a, b)  # Output: 32
print(dot_product)

[5 7 9]
[ 4 10 18]
32


|     Operator    |     Equivalent         |     Description                              |
|-----------------|------------------------|----------------------------------------------|
|     +           |     np.add             |     Addition   (e.g., 1 + 1 = 2)             |
|     -           |     np.subtract        |     Subtraction   (e.g., 3 - 2 = 1)          |
|     -           |     np.negative        |     Unary   negation (e.g., -2)              |
|     *           |     np.multiply        |     Multiplication   (e.g., 2 * 3 = 6)       |
|     /           |     np.divide          |     Division   (e.g., 3 / 2 = 1.5)           |
|     //          |     np.floor_divide    |     Floor   division (e.g., 3 // 2 = 1)      |
|     **          |     np.power           |     Exponentiation   (e.g., 2 ** 3 = 8)      |
|     %           |     np.mod             |     Modulus/remainder   (e.g., 9 % 4 = 1)    |

## Indexing and Slicing:
You can access elements and subarrays of a NumPy array using indexing and slicing:


In [4]:
arr = np.array([10, 20, 30, 40, 50])

# Accessing elements
print(arr[0])    # Output: 10
print(arr[-1])   # Output: 50

# Slicing
print(arr[1:4])  # Output: [20 30]

10
50
[20 30 40]


## Shape and Reshaping:
NumPy provides methods to get the shape of an array and to reshape arrays:


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Size : {}".format(arr.shape))
reshaped_arr = arr.reshape((3, 2))
print(reshaped_arr)

Size : (2, 3)
[[1 2]
 [3 4]
 [5 6]]


## Adding, removing, and sorting elements
In NumPy, you can easily add, remove, and sort elements in an array using various built-in functions and methods. Here's a brief explanation of each operation {cite:p}`harris2020array,NumPyDocumentation`:


### Adding Elements:
To add elements to a NumPy array, you can use functions like `numpy.append()` or `numpy.concatenate()`.

a. `numpy.append()`: This function appends elements to the end of an array. It creates a new array with the appended elements.

<font color='Blue'><b>Example</b></font>:

In [6]:
import numpy as np

arr = np.array([1, 2, 3])
new_element = 4
new_arr = np.append(arr, new_element)
print(new_arr)  # Output: [1 2 3 4]

[1 2 3 4]


b. `numpy.concatenate()`: This function concatenates two or more arrays along a specified axis.


<font color='Blue'><b>Example</b></font>:

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5])
combined_arr = np.concatenate((arr1, arr2))
print(combined_arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


### Removing Elements:
To remove elements from a NumPy array, you can use functions like `numpy.delete()` or filter the array based on certain conditions.

a. `numpy.delete()`: This function removes elements from an array along a specified axis.

<font color='Blue'><b>Example</b></font>:

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
index_to_remove = 2
new_arr = np.delete(arr, index_to_remove)
print(new_arr)  # Output: [1 2 4 5]

[1 2 4 5]


b. Filtering with Conditions: You can use boolean indexing to remove elements based on certain conditions.

<font color='Blue'><b>Example</b></font>:

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
condition = arr != 3
new_arr = arr[condition]
print(new_arr)  # Output: [1 2 4 5]

[1 2 4 5]


### Sorting Elements:
To sort elements in a NumPy array, you can use the `numpy.sort()` function.

<font color='Blue'><b>Example</b></font>:


In [10]:
import numpy as np

arr = np.array([3, 1, 5, 2, 4])
sorted_arr = np.sort(arr)
print(sorted_arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


Keep in mind that the above operations usually create a new array, so if you want to modify the original array in place, you can use appropriate assignment statements.

## Multi-dimensional arrays in NumPy

NumPy employs "ndarrays," which are multi-dimensional arrays, denoting "N-dimensional arrays." They serve as the cornerstone data structure for numerical computations within the library and excel in efficiently managing multi-dimensional data. With the capability to possess any number of dimensions, ndarrays facilitate working with diverse data shapes like vectors, matrices, or higher-dimensional arrays.
Diverse functions in NumPy enable the creation of multi-dimensional arrays, including `numpy.array()`, `numpy.zeros()`, `numpy.ones()`, and `numpy.random.rand()`, among several others {cite:p}`harris2020array,NumPyDocumentation`.

### Creating a 1-dimensional array:


In [11]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)
# Output: [1 2 3 4 5]

[1 2 3 4 5]


### Creating a 2-dimensional array (matrix):

In [12]:
import numpy as np

matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Creating a 3-dimensional array:

In [13]:
import numpy as np

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


You can access elements of multi-dimensional arrays using indexing, similar to regular Python lists. The number of indices you provide corresponds to the number of dimensions of the array.

In [14]:
import numpy as np

matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix_2d[1, 1])  # Output: 5
print(matrix_2d[0])     # Output: [1 2 3]
print(matrix_2d[:, 1])  # Output: [2 5 8] (second column)

5
[1 2 3]
[2 5 8]


NumPy also offers numerous functions for manipulating multi-dimensional arrays, including reshaping, slicing, mathematical operations, matrix operations, and more. Its capabilities are essential for scientific computing, data analysis, and machine learning tasks where multi-dimensional data is prevalent.

## Convert a 1D array into a 2D array

You can convert a 1D array into a 2D array in NumPy by adding a new axis using the `numpy.newaxis` attribute or the `numpy.expand_dims()` function. Both approaches achieve the same result of increasing the array's dimensions from 1D to 2D.

### Using `numpy.newaxis`
numpy.newaxis is a special attribute in NumPy that allows you to increase the dimensions of an array by adding a new axis. It is also represented by None. This new axis effectively converts a 1D array into a 2D array, a 2D array into a 3D array, and so on, depending on how many newaxis attributes you add {cite:p}`harris2020array,NumPyDocumentation`.

When you use numpy.newaxis in slicing operations, it adds a new axis at the specified position, effectively increasing the number of dimensions by one. This is particularly useful when you want to perform operations that require arrays with different dimensions to be compatible {cite:p}`harris2020array,NumPyDocumentation`.

Here's how numpy.newaxis works with an example:


In [18]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Convert to 2D array with new axis
arr_2d = arr_1d[:, np.newaxis]

print(arr_2d)
# Output:
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]]

[[1]
 [2]
 [3]
 [4]
 [5]]


### Using `numpy.expand_dims()`
`numpy.expand_dims()` is a function in NumPy that allows you to increase the dimensions of an array by inserting a new axis at a specified position. It is used to reshape arrays and increase their dimensionality. The function is quite flexible and can be used to add a new axis at any desired position.
Here's the syntax for `numpy.expand_dims()`:
numpy.expand_dims(a, axis)
Parameters:
- `a`: The input array to which a new axis will be added.
- `axis`: The position along which the new axis will be inserted. The axis parameter should be an integer or a tuple of integers.
Here's an example of using `numpy.expand_dims()`:

In [17]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Convert to 2D array with expand_dims
arr_2d = np.expand_dims(arr_1d, axis=1)

print(arr_2d)
# Output:
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]]

# Shape of arr_2d
print(arr_2d.shape)
# Output: (5, 1)

# Accessing elements of the 2D array
print(arr_2d[2, 0])

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
3


In this example, arr_1d is a 1D array with shape (5,). Using np.expand_dims(arr_1d, axis=1), we add a new axis at position axis=1, resulting in arr_2d, a 2D array with shape (5, 1). The new axis has been inserted as a new dimension along the vertical direction, converting the 1D array into a column vector.

numpy.expand_dims() is useful when you need to reshape arrays to make them compatible for certain operations or to bring them to a specific shape required by algorithms or functions.

## Computation on NumPy Arrays: Universal Functions

CPython, the default implementation of Python, can be slow in some operations due to its dynamic, interpreted nature. This flexibility in types prevents efficient compilation into machine code like in C and Fortran. To address this issue, projects like PyPy, Cython, and Numba have emerged. These projects aim to improve Python's performance through just-in-time compilation or code translation to C or LLVM bytecode. However, despite their strengths and weaknesses, none of these alternatives have surpassed the popularity of standard CPython. Python's sluggishness is most noticeable when performing repetitive tasks, like looping over arrays for element-wise operations. For example, calculating the reciprocal of values in an array can be a computationally intensive task {cite:p}`vanderplas2016python`.


Operator Equivalent universal functions	description {cite:p}`vanderplas2016python`:
    
|     Operator    |     Equivalent         |     Description                              |
|-----------------|------------------------|----------------------------------------------|
|     +           |     np.add             |     Addition   (e.g., 1 + 1 = 2)             |
|     -           |     np.subtract        |     Subtraction   (e.g., 3 - 2 = 1)          |
|     -           |     np.negative        |     Unary   negation (e.g., -2)              |
|     *           |     np.multiply        |     Multiplication   (e.g., 2 * 3 = 6)       |
|     /           |     np.divide          |     Division   (e.g., 3 / 2 = 1.5)           |
|     //          |     np.floor_divide    |     Floor   division                         |
|     **          |     np.power           |     Exponentiation   (e.g., 2 ** 3 = 8)      |
|     %           |     np.mod             |     Modulus/remainder   (e.g., 9 % 4 = 1)    |
|     +           |     np.add             |     Addition   (e.g., 1 + 1 = 2)             |
|     -           |     np.subtract        |     Subtraction   (e.g., 3 - 2 = 1)          |
|     *           |     np.multiply        |     Multiplication   (e.g., 2 * 3 = 6)       |
|     /           |     np.divide          |     Division   (e.g., 3 / 2 = 1.5)           |
|     //          |     np.floor_divide    |     Floor   division (e.g., 3 // 2 = 1)      |
|     **          |     np.power           |     Exponentiation   (e.g., 2 ** 3 = 8)      |
|     %           |     np.mod             |     Modulus/remainder   (e.g., 9 % 4 = 1)    |

In NumPy, `np.absolute(x)` is a function that computes the absolute value of the elements in the array `x`. The absolute value of a number is its distance from zero on the number line, so it always results in a non-negative value.

Here's how it works:

In [20]:
import numpy as np

# Example array
x = np.array([-2, -1, 0, 1, 2])

# Calculate the absolute value of each element in the array
abs_x = np.absolute(x)

print(abs_x)

[2 1 0 1 2]


A summary of NumPy functions {cite:p}`harris2020array,NumPyDocumentation`:

|     Function                |     Description                                                             |     Example                                             |
|-----------------------------|-----------------------------------------------------------------------------|---------------------------------------------------------|
|     numpy.array             |     Create an array from   a Python list or tuple.                          |     np.array([1,   2, 3])                               |
|     numpy.zeros             |     Create an array   filled with zeros.                                    |     np.zeros((3,   3))                                  |
|     numpy.ones              |     Create an array   filled with ones.                                     |     np.ones((2,   4))                                   |
|     numpy.empty             |     Create an uninitialized   array.                                        |     np.empty((2,   2))                                  |
|     numpy.arange            |     Create an array with   evenly spaced values within a given interval.    |     np.arange(0,   10, 2)                               |
|     numpy.linspace          |     Create an array with   evenly spaced values over a specified range.     |     np.linspace(0,   1, 5)                              |
|     numpy.eye               |     Create a 2-D array   with ones on the diagonal and zeros elsewhere.     |     np.eye(3)                                           |
|     numpy.reshape           |     Reshape an array to a   specified shape.                                |     np.reshape(array,   (2, 3))                         |
|     numpy.transpose         |     Permute the   dimensions of an array.                                   |     np.transpose(array)                                 |
|     numpy.concatenate       |     Join arrays along a   specified axis.                                   |     np.concatenate((array1,   array2), axis=0)          |
|     numpy.stack             |     Join arrays along a   new axis.                                         |     np.stack((array1,   array2))                        |
|     numpy.split             |     Split an array into   multiple sub-arrays.                              |     np.split(array,   4)                                |
|     numpy.add               |     Element-wise addition   of two arrays.                                  |     np.add(array1,   array2)                            |
|     numpy.subtract          |     Element-wise   subtraction of two arrays.                               |     np.subtract(array1,   array2)                       |
|     numpy.multiply          |     Element-wise   multiplication of two arrays.                            |     np.multiply(array1,   array2)                       |
|     numpy.divide            |     Element-wise division   of two arrays.                                  |     np.divide(array1,   array2)                         |
|     numpy.exp               |     Element-wise   exponential function.                                    |     np.exp(array)                                       |
|     numpy.log               |     Element-wise natural   logarithm.                                       |     np.log(array)                                       |
|     numpy.sqrt              |     Element-wise square   root.                                             |     np.sqrt(array)                                      |
|     numpy.sin               |     Element-wise sine   function.                                           |     np.sin(array)                                       |
|     numpy.cos               |     Element-wise cosine   function.                                         |     np.cos(array)                                       |
|     numpy.dot               |     Dot product of two   arrays.                                            |     np.dot(array1,   array2)                            |
|     numpy.sum               |     Sum of array   elements.                                                |     np.sum(array)                                       |
|     numpy.mean              |     Mean (average) of   array elements.                                     |     np.mean(array)                                      |
|     numpy.std               |     Standard deviation of   array elements.                                 |     np.std(array)                                       |
|     numpy.min               |     Minimum value in an   array.                                            |     np.min(array)                                       |
|     numpy.max               |     Maximum value in an   array.                                            |     np.max(array)                                       |
|     numpy.equal             |     Element-wise   comparison of two arrays for equality.                   |     np.equal(array1,   array2)                          |
|     numpy.logical_and       |     Element-wise logical   AND of two arrays.                               |     np.logical_and(array1,   array2)                    |
|     numpy.where             |     Return elements   chosen from two arrays depending on a condition.      |     np.where(condition,   x, y)                         |
|     numpy.argmax            |     Index of the maximum   value in an array.                               |     np.argmax(array)                                    |
|     numpy.argmin            |     Index of the minimum   value in an array.                               |     np.argmin(array)                                    |
|     numpy.resize            |     Resize an array to a   specified shape.                                 |     np.resize(array,   (3, 3))                          |
|     numpy.random.rand       |     Random values in a   given shape between 0 and 1.                       |     np.random.rand(3,   3)                              |
|     numpy.random.randint    |     Random integers from   low (inclusive) to high (exclusive).             |     np.random.randint(1,   100, size=(2, 2))            |
|     numpy.random.choice     |     Randomly sample   elements from an array.                               |     np.random.choice(array,   size=3, replace=False)    |
|     numpy.histogram         |     Compute the histogram   of a set of data.                               |     np.histogram(array,   bins=10)                      |
|     numpy.percentile        |     Compute the q-th   percentile of the data.                              |     np.percentile(array,   q=25)                        |
|     numpy.linalg.inv        |     Compute the   (multiplicative) inverse of a matrix.                     |     np.linalg.inv(matrix)                               |
|     numpy.linalg.det        |     Compute the   determinant of a matrix.                                  |     np.linalg.det(matrix)                               |
|     numpy.linalg.eig        |     Compute the   eigenvalues and right eigenvectors of a square array.     |     np.linalg.eig(matrix)                               |
|     numpy.linalg.svd        |     Singular value   decomposition of a matrix.                             |     np.linalg.svd(matrix)                               |
|     numpy.linalg.solve      |     Solve a linear matrix   equation.                                       |     np.linalg.solve(matrix,   vector)                   |

Please note that this table is not exhaustive, but it covers some common functions and their basic usage examples. For more details about each function and their parameters, you can refer to the official NumPy documentation at https://numpy.org/doc/.